### ISSUE TITLE
Episode 1 Feeback

### ISSUE THREAD

**Issue by thaophan1** [carpentries-incubator/twitter-with-twarc#10]
1. "Every user, tweet, video, and emoji on Twitter is data that can be collected and analyzed. In recent years Twitter analysis has become increasingly popular and has played a hand in predicting topics from natural disasters to Election outcomes."
     - this already sounds great, I think it would be better to give a specific example as well as a wow factor for the reader.

2. I like the restaurant analogy

**Comment by kristi-sara** [comment]
Thanks Thao
