### ISSUE TITLE
setup.md renata feedback

### ISSUE THREAD

**Issue by jonjab** [carpentries-incubator/twitter-with-twarc#13]
More screenshots.

My workflow was slightly different for “Making your Project and App” after verifying the email. The notification about access keys and reminders to save them were prompt before the dashboard and I had skip test an endpoint

edit the links to open as blank to prevent users to lose track of the setup page (I usually open with right click in a new tab but realized some people do not and get lost when they have multiple steps linked to external resources)

**Comment by kristi-sara** [comment]
links now open in sep tabs.
