### ISSUE TITLE
The archiving part of twarc

### ISSUE THREAD

**Issue by kristi-sara** [carpentries-incubator/twitter-with-twarc#16]
I showed one of the Japan carpentries members what we were up to (he asked) and one of the things he asked what part of the workshop we had an archiving part since its part of twarc. and I hadn't thought about that yet. Are we going to say anythign about the actual archiving?

**Comment by jonjab** [comment]
this is discussed a little bit in ep 2, and should be in ep 5, and is a major part of ep 9
