### ISSUE TITLE
App naming conventions in the Setup

### ISSUE THREAD

**Issue by kristi-sara** [carpentries-incubator/twitter-with-twarc#17]
We need to think of a way to name the apps because twitter doesnt allow apps with the same name 

twarc-app-(initials)(workshop date)? or is that too long?

**Comment by jonjab** [comment]
how about 'your-name'?

**Comment by apandas** [comment]
How about we let them name their app anything they want (and that they can rename it if they like). We would recommend twarc-app-[librarian nickname]. It's a bit silly, but if a learner can't think of their own app name then this is what they get.

Library Nickname generator:
a color you like + word that corresponds to your birth month

January - conservator
February - bibliothecary
March - curator
April - archivist
May - booklouse
June - annalist
July - cataloger
August - scholar
September - documenter
October - scribe
November - bookworm
December - bibliotaph

I'd be phthalo bibliothecary :)

**Comment by kristi-sara** [comment]
data wrangler?

**Comment by jonjab** [comment]
we must have already fixed the narrative, as we no longer recommend an app name. I made a very brief addition that says "app names need to be unique across the platform"
