### ISSUE TITLE
Ep 2 issues/suggestions 

### ISSUE THREAD

**Issue by gnunnelley** [carpentries-incubator/twitter-with-twarc#18]
**BergisJules**: Reached API Limit 3200 after running !twarc2 timeline BergisJules > 'source-data/bjules.jsonl'

**Terminal Commands:** For clarity purposes, explain what the terminal commands mean (e.g. **pwd** – print working directory, etc.) and add **mkdir** to that list in case attendees need to make a directory. Maybe reiterate how to use commands within terminal, e.g. “simply print the working directory by typing pwd into the terminal. If you are not inside **twarc-run**, change the current directory with **cd twarc-run.**” 

**twarc_csv**: error produced when importing twarc_csv despite using pip install and restarting the installation kernel for twarc_csv. Message: [https://ipywidgets.readthedocs.io/en/stable/user_install.html](https://ipywidgets.readthedocs.io/en/stable/user_install.html) <img width="609" alt="Screenshot 2022-05-09 150612" src="https://user-images.githubusercontent.com/72521430/167506664-f91c3511-c280-45eb-80de-f5e9a6d25043.png">

**Comment by kristi-sara** [comment]
changed everything but twarc_csv, we will probably not need that package becuase csv is a dependant package that is part of twarc
