### ISSUE TITLE
Ep3 issues/suggestions

### ISSUE THREAD

**Issue by gnunnelley** [carpentries-incubator/twitter-with-twarc#19]
For most of the 'tweet file creation' code lines, underscores should be hyphens to match folder names (e.g. source_data to source-data). Where/how to run the line 'head -n 2 source_data/taxday.jsonl > output_data/1-tweet.jsonl' is **unclear.**

**Comment by kristi-sara** [comment]
I think the files used to be source-data and are now raw_data so we have to go back and fix those

**Comment by jonjab** [comment]
the paths are all fixed. the head -m 2 part has been edited, and is on its way to being clear.
