### ISSUE TITLE
file naming convention

### ISSUE THREAD

**Issue by kristi-sara** [carpentries-incubator/twitter-with-twarc#20]
I feel like we're still flip flopping with the naming conventions. Is it source_data or raw_data? We need to redo all the screen shots if its now the latter.

**Comment by jonjab** [comment]
raw_data

that's why text is better than screenshots. we can hand updating all of the screenshots to the students over the weekend.

**Comment by kristi-sara** [comment]
keep working on fixing paths. I thought I got most of them
