### ISSUE TITLE
Ep 4 suggestions

### ISSUE THREAD

**Issue by gnunnelley** [carpentries-incubator/twitter-with-twarc#21]
- Under “What’s a lot” move !twarc2 common word counts to separate block

- Inconsistent naming conventions: e.g. ucsblib.jsonl vs ucsblib_timeline.jsonl

- Maybe move !twarc2 timeline --limit 500 UCSBLibrary > 'source-data/ucsblib.jsonl from where it is to ‘jsonl > csv > wc’ section for better flow. 

- Is list(kittens_df.columns) misplaced? 

- Everything else is good

**Comment by kristi-sara** [comment]
all kittens will be replaced with the ucsblib stuff

**Comment by kristi-sara** [comment]
can I just make it UCSB? ucsb library only throws out 20 something tweets

**Comment by jonjab** [comment]
> 

I wouldn't say all the kittens. there is still counts.

**Comment by kristi-sara** [comment]
all the kittens in episode 4. I thought we agreed on this this morning?

**Comment by jonjab** [comment]
> can I just make it UCSB? ucsb library only throws out 20 something tweets

timeline dude. we are downloading the timeline. 

I will clarify in the lesson while standardizing filenames.

**Comment by kristi-sara** [comment]
ok

**Comment by jonjab** [comment]
> can I just make it UCSB? ucsb library only throws out 20 something tweets

i see what you're saying. for sure we need something better at 'recent stream' where I was trying to do booleans. even the ucsb I saved in the notebook doesn't really do the trick for what we want here.

**Comment by jonjab** [comment]
I think this one can be closed with ep. 4 in its current state. there's still plenty of fixme's in there.
