### ISSUE TITLE
ep 2: bergis challenge

### ISSUE THREAD

**Issue by jonjab** [carpentries-incubator/twitter-with-twarc#22]
needs a solution.

harvest ecodatascience timeline.

**Comment by kristi-sara** [comment]
we're just getting the wordcount right? I think we've added the stuff for the timeline and its stalled at pandas dataframe (did we even need this for !twarc wc?)

**Comment by jonjab** [comment]
The challenge is these 3 questions:
Can you find the file called “bjules.jsonl”?
Download a timeline for one of the twitter accounts from this list: NCEAS “@ucsb_nceas”, EcoDataScience “@ecodatasci”, R-Ladies Santa Barbara “@RLadiesSB”, spatial@ucsb “@spatialUCSB”, UCSB Collaboratory “@libratorybot”

What do you notice about the file that was created from using the timeline command?





No word count. Pls write the solution for ecodatascience. Part of the solution should say "if you included the @ sign, you probably got an error"

**Comment by ameliameyer** [comment]
1. Can you find the file called bjules.jsonl?
- Remember, we ran the following code a little earlier in the episode:  
- `!twarc2 timeline BergisJules > 'raw_data/bjules.jsonl'`  
- Our output tag `raw_data/bjules.jsonl` indicates that our file `bjules.jsonl` is located in the folder `raw_data`.

**Comment by ameliameyer** [comment]
2. Download a timeline for one of the twitter accounts from this list: NCEAS “@ucsb_nceas”, EcoDataScience “@ecodatasci”, R-Ladies Santa Barbara “@RLadiesSB”, spatial@ucsb “@spatialUCSB”, UCSB Collaboratory “@libratorybot”
- `!twarc2 timeline ucsb_nceas ucsb_nceas_tweets.jsonl`
- `!twarc2 timeline ecodatasci ecodatasci_tweets.jsonl`
- `!twarc2 timeline RLadiesSB RLadiesSB_tweets.jsonl`
- `!twarc2 timeline spatialUCSB spatialUCSB_tweets.jsonl`
- `!twarc2 timeline libratorybot libratorybot_tweets.jsonl`
*Note: if you included the @ sign, you probably got an error*

**Comment by ameliameyer** [comment]
3. What do you notice about the file that was created using the timeline command?

*I'm not entirely sure what you're looking for with this one, but*

It's a jsonl file...
