### ISSUE TITLE
Download taxday.jsonl on Mac

### ISSUE THREAD

**Issue by thaophan1** [carpentries-incubator/twitter-with-twarc#23]
It's not very intuitive to download the .jsonl file from GitHub on Mac since as far as I know, it won't let me save it as anything other than a .txt file. If there is a way to do so, it would be really helpful to add it to the instructions. 

If not, I think the best way of going about it would be compressing the data into a zip folder and let the learner download it straight from the website.

**Comment by jonjab** [comment]
I put the data files on google drive so that they download directly.
