### ISSUE TITLE
Taxday download

### ISSUE THREAD

**Issue by thaophan1** [carpentries-incubator/twitter-with-twarc#25]
The transition to Google Drive for the taxday data download is very nice. However, I noticed that when I downloaded it normally from Google Drive, I ended up with a file named taxday.json.jsn. In order to get the correct .jsonl format, I had to enable Zip extractor (a Chrome extension). The Zip extractor step might not be intuitive so maybe we could add a comment about that or have the zip file on Github just like the twarc utilities because not everyone uses Google Chrome.

**Comment by jonjab** [comment]
I think taxday was that way because it was the last one on github. I have now pointed setup.md to the copy on google drive (ucsb authentication required), so it should work ok now. I also edited the language for setup.md a bit
