### ISSUE TITLE
twarc limits 

### ISSUE THREAD

**Issue by kristi-sara** [carpentries-incubator/twitter-with-twarc#26]
Amelia and I were wondering...

when we !twarc search --limit 500, we'll get a solid 500 tweets. When we limit it at 3000 or 5000 it'll give us a ball park of 3000 tweets (ex: 3087) or 5089 when I yanked it. When Amelia tried limiting under 100, it gave her 100. Should we add something this in the lesson?

**Comment by jonjab** [comment]
I’ve requested 500 and gotten 523, 506, etc. So I think we remain silent.

**Comment by kristi-sara** [comment]
Ok gotcha
