### ISSUE TITLE
ep7: Stopping the stream 

### ISSUE THREAD

**Issue by kristi-sara** [carpentries-incubator/twitter-with-twarc#30]
Is ctrl + C just a mac thing? Amanda and I couldnt stop it unless we interrupted the session

**Comment by ameliameyer** [comment]
I think it's a little different with Jupyter - assuming that's what you're using. You can press `i` twice when the cell is selected but not in editing mode and it aborts the twarc code currently running. 

But ctrl-c can be used on windows machines to either abort or copy something depending on the context. Not sure about other systems.

**Comment by jonjab** [comment]
you can also interrupt the kernel. I added that to the narrative.
