### ISSUE TITLE
ep6: Bash vs python kernel

### ISSUE THREAD

**Issue by kristi-sara** [carpentries-incubator/twitter-with-twarc#31]
is there a reason we're switching back to to the bashshell starting at the twitter search subheading? It wasn't clear to me why and when I ran the code in shell, it either threw out infinite output: twarc2 search "(archive AND data)" or it didnt throw out anything at all: twarc2 search "(to:ucsblibrary)".

**Comment by ameliameyer** [comment]
I think that might be an error. Those commands should still be run in the Jupyter python cells with "!" at the start to indicate they are command line arguments, right?

**Comment by kristi-sara** [comment]
Sticking with notebook kernels. closing.
