### ISSUE TITLE
ep 1: replace obscure tweet?

### ISSUE THREAD

**Issue by jonjab** [carpentries-incubator/twitter-with-twarc#32]
our one_tweet.jsonl is the area51 nehruta run tweet.

should we put that one in and talk about obscurity for a moment?

**Comment by ameliameyer** [comment]
We can. The obscure tweet there is mostly a placeholder.

**Comment by apandas** [comment]
I think that time in the introductions would benefit more from talking about retweets, quote tweets, likes, etc. 
suggested tweet to replace obscure tweets: https://twitter.com/Twitter/status/1300554631618220032

**Comment by jonjab** [comment]
^^^ I like Amanda's tweet.

**Comment by jonjab** [comment]
This is the embed code. Can I make it work in markdown?

<blockquote class="twitter-tweet"><p lang="en" dir="ltr">Three things—<br><br>1. &quot;Retweets with comments&quot; is changing to &quot;Quote Tweets&quot;<br><br>2. Quote Tweets will appear right next to Retweets<br><br>3. The mask goes over your nose <a href="https://t.co/x00YTZSAFs">pic.twitter.com/x00YTZSAFs</a></p>&mdash; Twitter (@Twitter) <a href="https://twitter.com/Twitter/status/1300554631618220032?ref_src=twsrc%5Etfw">August 31, 2020</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>

**Comment by jonjab** [comment]
embedded Amanda's suggested tweet (regarding a change in retweets vs retweets with quotes). We will harvest that conversation later in the lesson.
