### ISSUE TITLE
essential libraries

### ISSUE THREAD

**Issue by jonjab** [carpentries-incubator/twitter-with-twarc#6]
We need to put in a final request for python libraries. 

datetime
json -- i'm pretty sure it's there.
os ???
textblob

**Comment by jonjab** [comment]
request put in for these, except for json.

**Comment by jonjab** [comment]
textblob is working nicely. i haven't tested (don't know how) datetime.

**Comment by kristi-sara** [comment]
Can we close this now that Scott has published the JupyterHub Carpentry Instance?
