### ISSUE TITLE
Set Up Feedback

### ISSUE THREAD

**Issue by thaophan1** [carpentries-incubator/twitter-with-twarc#8]
1. taxday data download link is not working
2. for someone who doesn’t already have a twitter account or developer account, it would be useful if there was an embedded link that led them to the page to create a new account.
3. Under “Making your Project and App” it wasn’t very clear if I was supposed to make a new project after verifying my email address or not. Also, the instructions recommended using Academic researcher as the use case but this section talks about the ‘Exploring the API’ use case, caused a bit of confusion for me.
4. For me, the Twitter API uses the term ‘API Key’ instead of ‘Consumer Keys’

**Comment by jonjab** [comment]
I took care of 1, 2, and 4. please check.

**Comment by jonjab** [comment]
Kristi has edited ep. 0.

**Comment by jonjab** [comment]
@thaophan1  do you feel that setup is good and addresses all your issues?

**Comment by thaophan1** [comment]
Everything looks good now but the tax day link takes a long time to load because the link takes the user straight to the file. If it’s not too confusing for the user, I think it’s better to just lead them to the folder that stores the file. If not, it’s not a big deal

**Comment by kristi-sara** [comment]
Once I get all the files we will throw them into one folder to make it nice
