### ISSUE TITLE
Episode 2 Feedback

### ISSUE THREAD

**Issue by thaophan1** [carpentries-incubator/twitter-with-twarc#9]
1. Wasn’t able to test properly because the taxday download link wasn’t working
2. Tried to download taxday straight from the github page but it wouldn’t let me save as a .jsonl file, only as .txt
3. I made a mistake on Jupyter notebook
4. !twarc2 timeline BergisJules > ‘source-data/bjules.jsonl’ command and wasn’t able to run it a second time because on the second run, the API limit was reached. If this was supposed to only be a test command, maybe try a less intensive command that doesn’t make as many API calls.

**Comment by jonjab** [comment]
#4 still needs an explanation
And the challenge solution should include a temporal comparison of Bergius and the second a person’s timeline

**Comment by kristi-sara** [comment]
I thought the second timeline was the challenge at the bottom of the lesson?

**Comment by kristi-sara** [comment]
since we agreed on redoing the naming conventions Im going to start changing source-data to raw_data?

**Comment by jonjab** [comment]
> 

looks like all the text is change for raw_data and all the other original points on this one are competed.
